CREATE DATABASE PRUEBA;
USE PRUEBA;

CREATE TABLE TABLA_PRUEBA (
	ID INT NOT NULL AUTO_INCREMENT,
    NOMBRE VARCHAR(250),
    FECHA DATETIME,
    ESTATUS INT,
    PRIMARY KEY (ID)
);

CREATE TABLE ALUMNOS (
	ID INT NOT NULL AUTO_INCREMENT,
    ID_TABLA_PRUEBA INT,
    NOMBRE VARCHAR(250),
    APELLIDO VARCHAR(250),
    PRIMARY KEY (ID)
);


INSERT INTO TABLA_PRUEBA (NOMBRE, FECHA, ESTATUS) VALUES ('ANGEL', NOW(), 1);
INSERT INTO TABLA_PRUEBA (NOMBRE, FECHA, ESTATUS) VALUES ('FELIPE', NOW(), 1);
INSERT INTO ALUMNOS (NOMBRE, APELLIDO) VALUES ('JUAN', 'PEREZ');
INSERT INTO ALUMNOS (NOMBRE, APELLIDO) VALUES ('FELIPE', 'DEL ANGEL');

SELECT * FROM TABLA_PRUEBA;
SELECT * FROM ALUMNOS;

SELECT L1.NOMBRE, L1.APELLIDO, L2.NOMBRE, L2.APELLIDO FROM LISTA_GRUPOA L1 INNER JOIN LISTA_GRUPOB L2 INNER JOIN LISTA_GRUPOC L3 WHERE L1.FECHA = '2023/11/11' AND L1.ASISTIO = 1 OR L2.FECHA = '2023/11/11' AND L2.ASISTIO = 1;
SELECT T.NOMBRE, A.APELLIDO FROM TABLA_PRUEBA T INNER JOIN ALUMNOS A WHERE T.ID = A.ID;

UPDATE ALUMNOS SET NOMBRE = 'JOSE', APELLIDO = 'TERCERO' WHERE ID = 2;

DELETE FROM ALUMNOS WHERE ID = 2;

















CREATE TABLE USERS(
	ID INT NOT NULL auto_increment,
    TIMESTAMP DATETIME,
    primary key (ID)
);

CREATE TABLE NOTES(
	ID VARCHAR(50),
    ID_USER INT,
    TITLE VARCHAR(250),
    CONTENT VARCHAR(500),
    TIMESTAMP DATETIME,
    TYPE INT,
    COLOR INT
);


